application: cjallonboard
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: media/css

- url: /js
  static_dir: media/js

- url: /img
  static_dir: media/img

- url: /aob
  static_dir: media/aob

- url: /.*
  script: appengine.py
